# Generated by Django 4.0.1 on 2022-10-20 23:41

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from utilities.people_data_migration import initialize_database as people_init
from utilities.show_data_migration import initialize_database as show_init
from utilities.replay_data_migration import initialize_database as replay_init

class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_initial'),
        ('games', '0001_initial'),
        ('people', '0001_initial'),
        ('replay', '0001_initial'),
        ('shows', '0001_initial'),
        ('superreplay', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunPython(people_init),
        migrations.RunPython(show_init),
        migrations.RunPython(replay_init),
    ]
