# Generated by Django 4.0.1 on 2022-08-10 22:31

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from utilities.replay_data_migration import initialize_database as replay_init
from utilities.super_replay_data_migration import initialize_database as super_replay_init

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gamevideo_options'),
        ('people', '0002_initial'),
        ('replay', '0001_initial'),
        ('shows', '0003_remove_episode_show_episode_shows_and_more'),
        ('superreplay', '0002_alter_superreplaygame_options'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunPython(replay_init),
        migrations.RunPython(super_replay_init),
    ]
