# Generated by Django 4.0.1 on 2022-04-01 06:51

from django.db import migrations
from utilities.data_migration import initialize_database

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
        ('games', '0005_alter_platform_abbreviation',)
    ]

    operations = [
        migrations.RunPython(initialize_database),
    ]
