# Generated by Django 4.0.1 on 2022-06-28 05:27

from django.db import migrations
from utilities.data_migration import initialize_database

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
        # added dependency to enable models from 'game' app to initialize_database method
        ('games', '0005_alter_developer_id'),
    ]

    operations = [
        migrations.RunPython(initialize_database),
    ]
