# Generated by Django 4.0.1 on 2022-08-19 03:54

from django.db import migrations
from utilities.show_data_migration import initialize_database as show_init

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
        ('episodes', '0002_initial'),
        ('games', '0001_initial'),
        ('people', '0001_initial'),
        ('replay', '0001_initial'),
        ('shows', '0001_initial'),
        ('superreplay', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(show_init)
    ]