# Generated by Django 4.0.1 on 2022-07-08 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('people', '0001_initial'),
        ('fansite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superreplayepisode',
            name='featuring',
            field=models.ManyToManyField(blank=True, help_text='Enter people who feature in the episode (NOT including the host).', related_name='%(app_label)s_%(class)s_featuring_related', related_query_name='%(app_label)s_%(class)ss_featuring', to='people.Person'),
        ),
        migrations.AddField(
            model_name='superreplayepisode',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Enter person who hosts the episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_host_related', related_query_name='%(app_label)s_%(class)ss_host', to='people.person'),
        ),
        migrations.AddField(
            model_name='superreplayepisode',
            name='super_replay',
            field=models.ForeignKey(help_text='Enter Super Replay for this episode.', on_delete=django.db.models.deletion.CASCADE, to='fansite.superreplay'),
        ),
        migrations.AddField(
            model_name='superreplayepisode',
            name='youtube_video',
            field=models.OneToOneField(blank=True, help_text='Enter the YouTube video for the episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fansite.youtubevideo', verbose_name='YouTube Video'),
        ),
        migrations.AddField(
            model_name='segment',
            name='games',
            field=models.ManyToManyField(blank=True, help_text='Enter games played during the segment.', to='games.Game'),
        ),
        migrations.AddField(
            model_name='segment',
            name='type',
            field=models.ForeignKey(help_text='Enter type of segment.', on_delete=django.db.models.deletion.PROTECT, to='fansite.segmenttype'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='article',
            field=models.OneToOneField(blank=True, help_text='Enter article for the Replay episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fansite.article'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='external_links',
            field=models.ManyToManyField(blank=True, help_text='Enter any external URL links (NOT including Game Informer article OR YouTube video).', to='fansite.ExternalLink', verbose_name='External Links'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='featuring',
            field=models.ManyToManyField(blank=True, help_text='Enter people who feature in the episode (NOT including the host).', related_name='%(app_label)s_%(class)s_featuring_related', related_query_name='%(app_label)s_%(class)ss_featuring', to='people.Person'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Enter person who hosts the episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_host_related', related_query_name='%(app_label)s_%(class)ss_host', to='people.person'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='main_segment_games',
            field=models.ManyToManyField(help_text='Enter any games part of the main segment of the Replay episode.', to='games.Game', verbose_name='Main Segment Games'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='other_segments',
            field=models.ManyToManyField(blank=True, help_text='Enter other segments for the Replay episode.', to='fansite.Segment', verbose_name='Other Segments'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='season',
            field=models.ForeignKey(help_text='Enter season of the Replay episode.', on_delete=django.db.models.deletion.CASCADE, to='fansite.replayseason', verbose_name='Replay Season'),
        ),
        migrations.AddField(
            model_name='replayepisode',
            name='youtube_video',
            field=models.OneToOneField(blank=True, help_text='Enter the YouTube video for the episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='fansite.youtubevideo', verbose_name='YouTube Video'),
        ),
        migrations.AddField(
            model_name='headinginstance',
            name='heading',
            field=models.ForeignKey(help_text='Enter heading type.', on_delete=django.db.models.deletion.PROTECT, to='fansite.heading'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Enter person who authored the article.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person'),
        ),
    ]
