# Generated by Django 4.0.1 on 2022-08-08 05:47

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from utilities.super_replay_data_migration import initialize_database as super_replay_init

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
        ('games', '0003_remove_game_developer_remove_game_platform_and_more'),
        ('people', '0002_initial'),
        ('shows', '0002_alter_youtubevideo_duration_and_more'),
        ('superreplay', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunPython(super_replay_init),
    ]
