# Generated by Django 4.0.1 on 2022-03-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replayepisode',
            name='thumbnails',
        ),
        migrations.RemoveField(
            model_name='superreplayepisode',
            name='thumbnails',
        ),
    ]
