# Generated by Django 4.0.1 on 2022-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='replayepisode',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='segmenttype',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='superreplayepisode',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
