# Generated by Django 4.0.1 on 2022-07-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenttype',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description of segment.'),
        ),
    ]
