# Generated by Django 4.0.1 on 2022-03-01 19:45

from django.db import migrations
import fansite.models


class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='replayepisode',
            managers=[
                ('objects', fansite.models.ReplayEpisodeManager()),
            ],
        ),
    ]
