# Generated by Django 4.0.1 on 2022-08-13 06:10

from django.db import migrations
from utilities.show_data_migration import initialize_database as show_init

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
        ('games', '0004_alter_gamevideo_options'),
        ('people', '0002_initial'),
        ('replay', '0001_initial'),
        ('shows', '0005_alter_episode_runtime'),
        ('superreplay', '0002_alter_superreplaygame_options'),
    ]

    operations = [
        migrations.RunPython(show_init),
    ]
