# Generated by Django 4.0.1 on 2022-02-10 23:42

from django.db import migrations
from ..other_scripts.data_migration import initialize_database

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_database),
    ]
