# Generated by Django 4.0.1 on 2022-01-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replayepisode',
            name='external_links',
            field=models.ManyToManyField(blank=True, help_text='Enter any external URL links (NOT including Game Informer article OR YouTube video).', to='fansite.ExternalLink', verbose_name='external Links'),
        ),
        migrations.AlterField(
            model_name='replayepisode',
            name='featuring',
            field=models.ManyToManyField(blank=True, help_text='Enter staff members who feature in the episode (NOT including the host).', related_name='%(app_label)s_%(class)s_featuring_related', related_query_name='%(app_label)s_%(class)ss_featuring', to='fansite.Staff'),
        ),
        migrations.AlterField(
            model_name='replayepisode',
            name='guests',
            field=models.ManyToManyField(blank=True, help_text='Enter any other guests (NOT official staff members).', to='fansite.Guest'),
        ),
        migrations.AlterField(
            model_name='segmentinstance',
            name='games',
            field=models.ManyToManyField(blank=True, help_text='Enter games played during the segment.', to='fansite.Game'),
        ),
        migrations.AlterField(
            model_name='superreplayepisode',
            name='external_links',
            field=models.ManyToManyField(blank=True, help_text='Enter any external URL links (NOT including Game Informer article OR YouTube video).', to='fansite.ExternalLink', verbose_name='external Links'),
        ),
        migrations.AlterField(
            model_name='superreplayepisode',
            name='featuring',
            field=models.ManyToManyField(blank=True, help_text='Enter staff members who feature in the episode (NOT including the host).', related_name='%(app_label)s_%(class)s_featuring_related', related_query_name='%(app_label)s_%(class)ss_featuring', to='fansite.Staff'),
        ),
        migrations.AlterField(
            model_name='superreplayepisode',
            name='guests',
            field=models.ManyToManyField(blank=True, help_text='Enter any other guests (NOT official staff members).', to='fansite.Guest'),
        ),
    ]
