# Generated by Django 4.0.1 on 2022-03-20 22:32

from django.db import migrations
from utilities.data_migration import initialize_database

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0002_remove_replayepisode_thumbnails_and_more'),
        # added dependency to enable models from 'game' app to initialize_database method
        ('games', '0003_alter_game_release_date'),
    ]

    operations = [
        migrations.RunPython(initialize_database),
    ]
