# Generated by Django 4.0.1 on 2022-06-28 06:48

from django.db import migrations
from utilities.data_migration import initialize_database

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0002_alter_person_slug_alter_replayepisode_slug_and_more'),
        # added dependency to enable models from 'game' app to initialize_database method
        ('games', '0006_alter_developer_slug_alter_game_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(initialize_database),
    ]