# Generated by Django 4.0.1 on 2022-07-05 01:20

from django.db import migrations
from utilities.data_migration import initialize_database

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0002_alter_segmenttype_description'),
        # added dependency to enable models from 'game' app to initialize_database method
        ('games', '0002_alter_imageigdb_height_alter_imageigdb_width'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_database),
    ]
    