# Generated by Django 4.0.1 on 2022-06-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0002_auto_20220331_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name'], 'verbose_name_plural': 'people'},
        ),
    ]
