# Generated by Django 4.0.1 on 2022-03-01 19:45

from django.db import migrations
from fansite.other_scripts.data_migration import initialize_database

class Migration(migrations.Migration):

    dependencies = [
        ('fansite', '0002_alter_replayepisode_managers'),
        # added dependency to enable models from 'game' app to initialize_database method
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_database),
    ]
