# Generated by Django 4.0.1 on 2022-07-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter name of YouTube tag.', max_length=50)),
            ],
            options={
                'verbose_name': 'YouTube Tag',
            },
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='Enter YouTube video ID.', max_length=15, verbose_name='Video ID'),
        ),
    ]
