# Generated by Django 4.0.1 on 2022-08-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superreplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superreplaygame',
            options={'verbose_name': 'Super Replay Game'},
        ),
    ]
