# Generated by Django 4.0.1 on 2022-07-18 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter full name (maximum 100 characters).', max_length=100, verbose_name='Full Name')),
                ('short_name', models.CharField(blank=True, help_text='Enter optional short name variation for usage in correspondence (maximum 50 characters).', max_length=50, verbose_name='Short Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('headings', models.JSONField(blank=True, help_text='Enter JSON of different headings with key being the heading title and value being the content.', null=True)),
                ('infobox_details', models.JSONField(blank=True, help_text='Enter JSON of different headings with key being the heading title and value being the content.', null=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title of position.', max_length=200)),
            ],
            options={
                'verbose_name': 'Staff Position',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StaffPositionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField(help_text='Enter date started the position.', verbose_name='Start Year')),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text='Enter date started the position.', null=True, verbose_name='End Year')),
                ('position', models.ForeignKey(help_text='Enter position of the staff member.', on_delete=django.db.models.deletion.PROTECT, to='people.staffposition')),
                ('staff', models.ForeignKey(help_text='Enter staff member for this position instance.', on_delete=django.db.models.deletion.CASCADE, to='people.staff')),
            ],
            options={
                'verbose_name': 'Staff Position Instance',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
