# Generated by Django 4.0.1 on 2022-08-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='duration',
            field=models.CharField(blank=True, help_text='Enter video duration in format: ex. PT1H34M35S.', max_length=10),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='published_at',
            field=models.DateField(blank=True, help_text='Enter date the YouTube video was published.', null=True),
        ),
    ]
