# Generated by Django 4.0.1 on 2022-08-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_youtubevideo_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='show',
        ),
        migrations.AddField(
            model_name='episode',
            name='shows',
            field=models.ManyToManyField(blank=True, help_text='Enter shows that include the episode.', to='shows.Show'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='youtube_video',
            field=models.OneToOneField(blank=True, help_text='Enter YouTube video of the episode.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shows.youtubevideo'),
        ),
    ]
