# Generated by Django 4.0.1 on 2022-08-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_remove_episode_show_episode_shows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='duration',
            field=models.CharField(blank=True, help_text='Enter video duration in format: ex. PT1H34M35S.', max_length=11),
        ),
    ]
