# Generated by Django 4.0.1 on 2022-08-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_youtubevideo_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='runtime',
            field=models.CharField(blank=True, help_text='Enter episode runtime in format hh:mm:ss.', max_length=11),
        ),
    ]
