# Generated by Django 4.0.1 on 2022-03-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(help_text='Enter date the game was released.', verbose_name='Release Date'),
        ),
    ]
