# Generated by Django 4.0.1 on 2022-07-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageigdb',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the height of the image in pixels.', null=True),
        ),
        migrations.AlterField(
            model_name='imageigdb',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the width of the image in pixels.', null=True),
        ),
    ]
