# Generated by Django 4.0.1 on 2022-06-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, help_text='Enter the IGDB website address (URL) of the game.'),
        ),
    ]
