# Generated by Django 4.0.1 on 2022-07-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Official'), (2, 'Wikia'), (3, 'Wikipedia'), (4, 'Facebook'), (5, 'Twitter'), (6, 'Twitch'), (8, 'Instagram'), (9, 'Youtube'), (10, 'Iphone'), (11, 'Ipad'), (12, 'Android'), (13, 'Steam'), (14, 'Reddit'), (15, 'Itch'), (16, 'Epicgames'), (17, 'Gog'), (18, 'Discord')])),
                ('trusted', models.BooleanField(default=False)),
                ('url', models.URLField(help_text='Enter the IGDB website address (URL) of the item.')),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.PositiveSmallIntegerField(help_text='Enter IGDB ID for the genre.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter name of the genre.', max_length=200),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(help_text='Enter the game.', on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.OneToOneField(help_text='Enter the IGDB Image.', on_delete=django.db.models.deletion.CASCADE, to='games.imageigdb'),
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Enter IGDB ID of the video.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the video.', max_length=200)),
                ('video_id', models.CharField(help_text='Enter the external ID of the video (usually YouTube).', max_length=50)),
                ('game', models.ForeignKey(help_text='Enter the game.', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Enter IGDB ID of the %(class).', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name of the %(class).', max_length=200)),
                ('slug', models.SlugField(help_text='Enter a url-safe, unique, lower-case version of the %(class).', max_length=200, unique=True)),
                ('url', models.URLField(help_text='Enter the IGDB website address (URL) of the %(class).')),
                ('games', models.ManyToManyField(help_text='Enter games part of the %(class).', to='games.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.PositiveIntegerField(help_text='Enter IGDB ID of the %(class).', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name of the %(class).', max_length=200)),
                ('slug', models.SlugField(help_text='Enter a url-safe, unique, lower-case version of the %(class).', max_length=200, unique=True)),
                ('url', models.URLField(help_text='Enter the IGDB website address (URL) of the %(class).')),
                ('games', models.ManyToManyField(help_text='Enter games part of the %(class).', to='games.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(help_text='Enter the game.', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('image', models.OneToOneField(help_text='Enter the IGDB Image.', on_delete=django.db.models.deletion.CASCADE, to='games.imageigdb')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='websites',
            field=models.ManyToManyField(blank=True, help_text='Enter websites associated with the game.', to='games.Website'),
        ),
    ]
