# Generated by Django 4.0.1 on 2022-07-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_website_alter_genre_id_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevideo',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the name of the video.', max_length=200),
        ),
    ]
