# Generated by Django 4.0.1 on 2022-07-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_collection_id_alter_developer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='developer',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Enter date the company was founded.', null=True, verbose_name='Release Date'),
        ),
        migrations.AddField(
            model_name='developer',
            name='websites',
            field=models.ManyToManyField(blank=True, help_text='Enter companies official websites.', to='games.Website'),
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, help_text='Enter developers of the game.', to='games.Developer'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, help_text='Enter game platforms (ex. PC, PS4, XBox 360, etc.).', to='games.Platform'),
        ),
        migrations.AddField(
            model_name='platform',
            name='generation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter the generation of the system/platform.', null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='websites',
            field=models.ManyToManyField(blank=True, help_text='Enter websites associated with the system/platform.', to='games.Website'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Enter shortened abbreviation for the system/platform.', max_length=20),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Enter logo of the first Version of the platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.imageigdb'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a summary of the first Version of the platform.'),
        ),
    ]
