# Generated by Django 4.0.1 on 2022-08-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_developer_remove_game_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamevideo',
            options={'verbose_name': 'Video'},
        ),
    ]
