# Generated by Django 4.0.1 on 2022-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='alternate_name',
            field=models.CharField(blank=True, help_text='Enter alternate names as list separated by commas.', max_length=1000),
        ),
    ]
