# Generated by Django 4.0.1 on 2022-06-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_developer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.PositiveIntegerField(help_text='Enter IGDB ID of the company.', primary_key=True, serialize=False),
        ),
    ]
