# Generated by Django 4.0.1 on 2022-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_developer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(help_text='Enter a url-safe, unique, lower-case version of the company.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(help_text='Enter a url-safe, unique, lower-case version of the platform.', max_length=200, unique=True),
        ),
    ]
