# Generated by Django 4.0.1 on 2022-06-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_platform_abbreviation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
    ]
